version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
  - README.md
  - CHANGELOG.md
  - .editorconfig
  - .gitignore
  - renovate.json

max_jobs: 1

image: Visual Studio 2019

install:
- Install-Product node lts x64
- yarn install --frozen-lockfile

build_script:
- yarn build

artifacts:
- path: bin/*.nupkg

cache:
- node_modules
- '%LOCALAPPDATA%/Yarn'
